#!/usr/bin/env bash
# generate-compose.sh — Generates docker-compose.yml for a Komga container
# Usage: bash generate-compose.sh [--output <path>] [--non-interactive]

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────
OUTPUT="docker-compose.yml"
NON_INTERACTIVE=false

KOMGA_PORT=25600
KOMGA_DATA_DIR="./komga/data"
KOMGA_CONFIG_DIR="./komga/config"
MEDIA_DIR="./media"
TZ="Europe/London"

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)   OUTPUT="$2"; shift 2 ;;
        --non-interactive) NON_INTERACTIVE=true; shift ;;
        --help)
            echo "Usage: $0 [--output <path>] [--non-interactive]"
            echo ""
            echo "Options:"
            echo "  --output <path>       Output file path (default: docker-compose.yml)"
            echo "  --non-interactive     Use all defaults without prompting"
            exit 0
            ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# ── Prompt helper (skipped in non-interactive mode) ───────────────────────────
prompt() {
    local var_name="$1"
    local label="$2"
    local default="${!var_name}"

    if [[ "$NON_INTERACTIVE" == true ]]; then
        return
    fi

    read -rp "${label} [${default}]: " input
    if [[ -n "$input" ]]; then
        printf -v "$var_name" '%s' "$input"
    fi
}

# ── Interactive configuration ─────────────────────────────────────────────────
if [[ "$NON_INTERACTIVE" == false ]]; then
    echo ""
    echo "=== Komga docker-compose generator ==="
    echo "Press Enter to accept each default shown in [brackets]."
    echo ""
fi

prompt TZ               "Timezone (TZ)"
prompt KOMGA_PORT       "Komga host port"
prompt KOMGA_CONFIG_DIR "Komga config directory (host path)"
prompt KOMGA_DATA_DIR   "Komga data directory (host path)"
prompt MEDIA_DIR        "Media directory (host path)"

# ── Write docker-compose.yml ──────────────────────────────────────────────────
cat > "$OUTPUT" <<YAML
# Generated by generate-compose.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Komga docs: https://komga.org/docs/installation/docker

services:

  komga:
    image: gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    ports:
      - "${KOMGA_PORT}:25600"
    volumes:
      - ${KOMGA_CONFIG_DIR}:/config
      - ${KOMGA_DATA_DIR}:/data
      - ${MEDIA_DIR}:/media:ro
    environment:
      - TZ=${TZ}
    # Admin UI: http://localhost:${KOMGA_PORT}
    # REST API: http://localhost:${KOMGA_PORT}/api/v1/

# ── Named volumes (optional — comment out above bind mounts and use these
#    instead if you prefer Docker-managed storage) ─────────────────────────────
# volumes:
#   komga_config:
#   komga_data:
YAML

echo ""
echo "Written: ${OUTPUT}"
echo ""
echo "Next steps:"
echo "  1. Review ${OUTPUT} and adjust volume paths as needed"
echo "  2. docker compose up -d"
echo "  3. Open Komga at http://localhost:${KOMGA_PORT} and create an admin account"
echo "  4. In Komga: Account → API Keys → create a key for the Jellyfin plugin"
